fixtures:
  repositories:
    inifile: 'git://github.com/puppetlabs/puppetlabs-inifile.git'
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    postgresql: 'git://github.com/puppetlabs/puppet-postgresql.git'
    firewall: 'git://github.com/puppetlabs/puppetlabs-firewall.git'
    apt: 'git://github.com/puppetlabs/puppetlabs-apt.git'
    concat: 'git://github.com/puppetlabs/puppetlabs-concat.git'
    file_concat: 'git://github.com/electrical/puppet-lib-file_concat.git'
    systemd: 'git://github.com/camptocamp/puppet-systemd.git'
    cron: 'git://github.com/voxpupuli/puppet-cron.git'
    cron_core: https://github.com/puppetlabs/puppetlabs-cron_core.git
    yumrepo_core: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
    augeas_core: https://github.com/puppetlabs/puppetlabs-augeas_core.git
